{% set name = "pyhocon" %}
{% set version = "0.3.61" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/chimpler/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 1354d772e990076d111c7da2412ee031387fcd9dfeb5e4359c68d887c0ac8f57

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pyhocon=pyhocon.tool:main

requirements:
  host:
    - pip
    - python {{ python_min }}

  run:
    - python >={{ python_min }}
    - pyparsing >=2,<4

test:
  imports:
    - pyhocon

  commands:
    - pip check
    - pyhocon --help

  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/chimpler/pyhocon/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: HOCON parser for Python
  description: HOCON parser for Python
  doc_url: https://pythonhosted.org/pyhocon/
  dev_url: http://github.com/chimpler/pyhocon/

extra:
  recipe-maintainers:
    - nelson-liu
    - shahin
    - thewchan
