{% set name = "pyhocon" %}
{% set version = "0.3.63" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/chimpler/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 93b16d7a59cb79a9728e8e1eeefe00b3614ead77e3c9f873ec3cafe61fe64a49

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pyhocon=pyhocon.tool:main

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}

  run:
    - python >={{ python_min }}
    - pyparsing >=2,<4

test:
  imports:
    - pyhocon

  commands:
    - pip check
    - pyhocon --help

  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/chimpler/pyhocon/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: HOCON parser for Python
  description: HOCON parser for Python
  doc_url: https://pythonhosted.org/pyhocon/
  dev_url: http://github.com/chimpler/pyhocon/

extra:
  recipe-maintainers:
    - nelson-liu
    - shahin
    - thewchan
