{% set pkgname = "pyhocon" %}
{% set version = "0.3.60" %}

package:
  name: {{ pkgname }}
  version: {{ version }}

source:
  fn: {{ pkgname }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pkgname[0] }}/{{ pkgname }}/{{ pkgname }}-{{ version }}.tar.gz
  sha256: ea18520ea126981e5320a72281f1a5fef2c27923f70cc54e1bd241c26525fd4b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pyhocon=pyhocon.tool:main

requirements:
  host:
    - pip
    - python >=3.6
    - pyparsing >=2.0.3
    - asset
    - setuptools

  run:
    - python >=3.6
    - pyparsing >=2.0.3
    - asset
    - setuptools

test:
  imports:
    - pyhocon

  commands:
    - pyhocon --help

about:
  home: http://github.com/chimpler/pyhocon/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: HOCON parser for Python
  description: HOCON parser for Python
  doc_url: https://pythonhosted.org/pyhocon/
  dev_url: http://github.com/chimpler/pyhocon/

extra:
  recipe-maintainers:
    - nelson-liu
    - shahin
